### ISSUE TITLE
Should img.php have at least some basic authentication and authorization check?

### ISSUE THREAD

**Issue by mudrd8mz** [abautu/moodle-datafield_jsignature#1]
It does not seem right that this scripts provides the functionality to anonymous internet users. Maybe there should be a mechanism for some basic authentication / authorisation?

**Comment by abautu** [comment]
I added an authorization step when image URL is generated/requested. It is an md5 of the main URL and the siteidentifier. I don't plan to do authentication as I believe the image should be available for non-authenticated users, too.
Thank you again for your feedhack and help!
