### ISSUE TITLE
Please add support for Moodle mobile app

### ISSUE THREAD

**Issue by phxgbl** [abautu/moodle-datafield_jsignature#4]
@abautu  your plugin works perfectly in the browser but is not compatible with the mobile app since the db/mobile.php is missing. jquery and AMD are also not supported.   Do you have any plans to extend support to mobile as well?

[mobile ref](https://docs.moodle.org/dev/Moodle_App_Plugins_Development_Guide)

**Comment by phxgbl** [comment]
Not possible for latest moodle mobile app
https://moodle.org/mod/forum/discuss.php?d=429576#p1739774
https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-73238

**Comment by abautu** [comment]
@phxgbl Thank you for researching this.
